### ISSUE TITLE
Basic functionality not working

### ISSUE THREAD

**Issue by MaralWa** [jakewvincent/mkdnflow.nvim#105]
Hi,

I am a long time user of VimWiki and hoped that mkdnflow could be a LUA based replacement for VimWiki. But for me mkdnflow is not working at all. The folldwing lines are from the index file of my main Wiki:

```
[Abonnements](Abonnements)
[[Abonnements]]
```

With VimWiki, if I place the cursor somewhere within the links and hit `<CR>`, the linked note `Abonnements.md` is opened by nvim. If I deactivate VimWiki and do the same with mkdnflow, the cursor just moves to the next line. Also mkdnflow does not conceal the links. Also mkdnflow does not conceal Wiki-links like VimWiki does.

I am using NeoVim Release v0.8.0. My NeoVim configuration is based on my [fork of nvim-basic-ide](https://github.com/MaralWa/nvim-basic-ide).

I added this locally to my plugins.lua:

```
 use({'jakewvincent/mkdnflow.nvim',
     rocks = 'luautf8', -- Ensures optional luautf8 dependency is installed
     config = function()
         require('mkdnflow').setup({})
     end
 })
```

When I start nvim, I see no errors, but `:PackerSync`  produces these messages: 

```
E5108: Error executing lua Vim:Error executing Lua callback: ...im/site/pack/packer/start/mkdnflow.nvim/lua/mkdnflow.lua:240: loop or previous error loading module 'mkdnflow
.tables'
stack traceback:
        [C]: in function 'require'
        ...im/site/pack/packer/start/mkdnflow.nvim/lua/mkdnflow.lua:240: in function 'setup'
        ...im/site/pack/packer/start/mkdnflow.nvim/lua/mkdnflow.lua:281: in function 'forceStart'
        ...site/pack/packer/start/mkdnflow.nvim/plugin/mkdnflow.lua:29: in function <...site/pack/packer/start/mkdnflow.nvim/plugin/mkdnflow.lua:29>
        [C]: in function 'execute'
        ...ite/pack/packer/start/packer.nvim/lua/packer/display.lua:996: in function 'quit'
        [string ":lua"]:1: in main chunk
stack traceback:
        [C]: in function 'execute'
        ...ite/pack/packer/start/packer.nvim/lua/packer/display.lua:996: in function 'quit'
        [string ":lua"]:1: in main chunk
```

Ciao

Maral

**Comment by jakewvincent** [comment]
Hi. This is probably due to something in the config you've copied, rather than a mkdnflow issue. The following may be related: https://github.com/jakewvincent/mkdnflow.nvim/issues/49. I'd recommend trying mkdnflow with a minimal config first or trying to disable the other plugins enabled in your config one by one and seeing which (if any) might be interfering.

This plug-in is not a one-for-one, drop-in replacement for Vimwiki. Please do a Ctrl+f in the readme for 'conceal' to see how to enable link concealing. Mkdnflow only offers concealing of wiki-style links and markdown-style links. If you want any other markdown elements concealed and have treesitter enabled, as well as the two markdown parsers, you can actually just enable concealing for markdown files (`:h conceallevel`) and you will get links and a number of other elements concealed out of the box.

**Comment by MaralWa** [comment]
Hi,
thank you for your reply. Indeed `impatient` seems to cause the problem in my config, too. I just removed it from my configuration and can now follow links with `<cr>`. And I could also activate concealing for links. I think I misunderstood the website and thought that links were concealed by default.
Ciao
Maral
