### ISSUE TITLE
New type of link 'source'

### ISSUE THREAD

**Issue by olesendan** [jakewvincent/mkdnflow.nvim#11]
Hi Jake.

I would like to use your plugin. for my personal knowledge system(PKS). I imaging that I have a root folder the PKS.

Could you imaging that there is another type of link. to (papers, documentations, websites) which is not saved relative to the PKS. ex. another folder where I have my library of papers. Maybe another project where I have education materials.

I would like to be able to do something link [link to source](source:/home/dano/doc/mat.xlsx) or [paper](source:~/library/paper.pdf) or [website](source:www.paper.com]

I can take a stab of trying to implement a solution from what you already have build. But I havn't done anything in Lua before, an is a novice programmer.

Greetings from denmark
Dan Olesen

**Comment by jakewvincent** [comment]
Hi Dan, thanks for submitting an issue! This is actually something I would like to add to the plugin as well. Here's my thinking on this: instead of adding a new link type, the link handler will look for paths that start with ~ or / (or X:\ on Windows) and know not to interpret those relative to the directory of the current or first-opened file. Do you imagine that would cover your use case?

**Comment by olesendan** [comment]
Hi Jake.

I think this will work really well. I've just been catching up on markdown syntax. Your proposal is better than mine, and I think it is a good fit to how footnotes is implemented in markdown [1] and [1]: [link to paper](~/library/paper.pdf)

If you can point me towards some documentation for Lua, I can try to take a stab on a solution.

Greetings from denmark
Dan Olesen

**Comment by jakewvincent** [comment]
I think I have a working solution (for using absolute paths outside of your PKS directory or paths relative to a home directory). I'll push the update later today after a bit more testing. I realized that it would make the most sense to add this functionality to links with the `file:` prefix. After re-reading your issue though, I realized that you're looking for a more semantically oriented prefix, i.e. one that helps you categorize links according to their role in your document, rather than their inherent properties (markdown or text file, vim-external file, web address). Currently, what you would like to label `source:` is most likely to be either `file`: or a web address. Since the only prefix I've implemented is only used to assist with opening external files, I'd like to keep the set of prefixes minimal and based on functionality.

As an academic, though, I am definitely sympathetic to what you're looking for, and I'm wondering if there's an alternative system we could implement. Do you know if there are any standard markdown flavors that specify a standard for adding tags to links or other parts of markdown documents?

**Comment by jakewvincent** [comment]
I've committed some changes that will allow absolute paths (starting with `/` and paths starting with `~/`) as long as the path in the link is prefixed with `file:`. Let me know if you have any thoughts on my previous comment, @olesendan--still interested if you have any ideas!

**Comment by olesendan** [comment]
Hi Jake.

This sounds great. I will test the file prefix. I will open a new issue for citations. I have a idea, that we can discuess.

greetings from denmark.
Dan Olesen
