### ISSUE TITLE
Feature: Autocompletions for filepaths, tags, headers, ____?

### ISSUE THREAD

**Issue by m-faith** [jakewvincent/mkdnflow.nvim#138]
I saw https://github.com/jakewvincent/mkdnflow.nvim/issues/89 exists and completions would be great to have for filepaths as well as tags. I can't think of any other autocompletions... oh, well... I guess taskwarrior completions to make a markdown list item for a taskwarrior task, but that's getting carried away.

**Comment by m-faith** [comment]
I don't really know how this works... should https://github.com/artempyanykh/marksman and LSP be used? I know there's also some kind of nvim-cmp or lua-cmp completions plugin too...

**Comment by jakewvincent** [comment]
I have thought about adding in some autocompletion features for quite a while, but I'm afraid I'd need to find someone who could support this or at least make this lower priority than some of the other feature requests because I have no clue how custom completion works and would need to do some research.

For filepath completion, I myself use nvim-cmp with cmp-path and it works well. For tags, you can use cmp-buffer, but that only helps if there's already an instance of the tag in your buffer. If you have a fixed list of tags you use, you could look into setting up a custom completion source for nvim-cmp, although I admit I have t done that before and don't know what exactly is involved.

**Comment by saccarosium** [comment]
Could try to implemented myself. I will need to do some reasearch for somethings but I could doit.

**Comment by kvngvikram** [comment]
Hi, 
I implemented a nvim-cmp [source](https://github.com/kvngvikram/cmp-mkdnflow)  and also integrated it in this [pull request](https://github.com/jakewvincent/mkdnflow.nvim/pull/165).

Mind you that the pull request also has support for autocompleting citation keys from bib file. I kind of copied [cmp-pandoc-references](https://github.com/jc-doyle/cmp-pandoc-references) but with auto detection of bib files.

BUT. For autocompleting links, I just do a file system search for markdown files. 
NOT tags. 
I actually feel that full text search of all files in the notebook to include all the possible requirements. But I don't know if that's a good idea.

Anyway, I will switch if there is a better way. Is anyone else working on similar thing ?

**Comment by saccarosium** [comment]
> Anyway, I will switch if there is a better way. Is anyone else working on similar thing ?

It was on my backlog but I didn't found time to work on it.
