### ISSUE TITLE
In readme, seems like nvim_wd_heel should be vimwd_heel

### ISSUE THREAD

**Issue by Euthoniel** [jakewvincent/mkdnflow.nvim#48]
I didn't want a change in perspective to change the working directly. I tried switching nvim_wd_heel to false, but it did nothing. I looked at the code a bit, set vimwd_heel to false in my config, and the functionality was disabled as expected.

**Comment by jakewvincent** [comment]
Thanks for reporting this! It's all consistently `nvim_wd_heel` now. (`vimwd_heel` will still work for now--the compat module will convert it to `nvim_wd_heel` if it finds the `vimwd_heel` key.)

**Comment by idr4n** [comment]
Hi and thanks for this cool plugin!

It seems like `nvim_wd_heel` is not working for me either (I just installed your plugin) . This is my perspective setting:

```lua
perspective = {
	priority = "root",
	fallback = "root",
	root_tell = ".wiki_root",
	nvim_wd_heel = false,
},
```

Say that I start an nvim session in cwd `~/foo` which is not a wiki directory (it doesn't have a`.wiki_root` file). Then I start editing a note in a subdirectory, say `~/foo/bar/note.md`, then nvim's current working directory changes to `~/foo/bar`, but I want it to stay in `~/foo`.

The only way in which I have managed to get the behavior I want is with `fallback = false`, irrespective of `nvim_wd_heel` being set to `true` or `false`. Could you please clarify if this is the expected behavior? I'm asking as I didn't see in the documentation that `fallback = false` is a valid setting.

Thanks in advance!

**Comment by jakewvincent** [comment]
Hi @idr4n, thanks for trying out the plugin! Oddly, I can't reproduce this. `false` is not technically a valid setting for `fallback`, but I don't know if it will specifically cause any issues--you could probably keep it like that. When you start editing the note in the subdirectory, how are you opening that note? Are you following it using the plugin's mappings, or are you opening it with another tool, such as Telescope?

**Comment by idr4n** [comment]
Hi and thanks for the quick reply.

Yes, I open the note with Telescope or fzf.vim. By plugin mapping you mean with `<CR>` when on top of a link?

**Comment by jakewvincent** [comment]
Right, that's what I meant. I think it may be Telescope/fzf that is changing your working directory since I can't reproduce this on my end. I double-checked the function that changes working directory and can't see any accidental loopholes that would cause mkdnflow to change working directories without `nvim_wd_heel` being true. Can you run the following for me from a vim session just to make sure that your `nvim_wd_heel` setting is correctly recognized?

`lua print(require('mkdnflow').config.perspective.nvim_wd_heel)`

**Comment by idr4n** [comment]
Hi again,

`lua print(require('mkdnflow').config.perspective.nvim_wd_heel)` prints `false`.

>  I think it may be Telescope/fzf that is changing your working directory since I can't reproduce this on my end.

It might be something in my config. However, without your plugin installed, Telescope/fzf does not change my working directory, it only happens when your plugin is installed/enable.

Don't worry, however, I have been using `fallback` set to `false` and at least for now I have not encountered issues with that.

Thanks again and feel free to close this issue then.

**Comment by jakewvincent** [comment]
I see, how strange! Let me do a little more testing (with Telescope) to see if I can reproduce this and what might be causing the working directory change.

**Comment by jakewvincent** [comment]
Still having trouble reproducing this, even with Telescope and various perspective settings. At first I thought maybe the plugin was being initialized each time you're switching buffers using Telescope, but it doesn't seem like that's happening in testing. In a session with mkdnflow enabled, what do you get when you issue `:set autochdir?` (including the question mark)?

**Comment by idr4n** [comment]
`:set autochdir?` prints `noautochdir`. 

If you are not being able to reproduce this don't worry then, it might be some hidden setting in my config. I will explore it on my side. Thanks again!

**Comment by jakewvincent** [comment]
Huh, puzzling! Please do comment again if you figure out what's causing it.

**Comment by dzirtusss** [comment]
@jakewvincent @idr4n 

Exactly this problem was as well troubling me and I've wrapped:
https://github.com/jakewvincent/mkdnflow.nvim/blob/683c358434d6e7534ab6ba125b6926cd28a858ae/lua/mkdnflow.lua#L252

as:
```lua
if not perspective.nvim_wd_heel then
  vim.api.nvim_set_current_dir(init.root_dir)
end
```

And the problem gone.

I've not heavily tested, but root works, and sub-root works as described by topic starter. Dunno if this affects other functionality, but all seems working.

Actually there are several more `nvim_set_current_dir` below in the repo. Maybe worth extracting ALL them to:
```lua
funtion safe_cd(dir)
  if not perspective.nvim_wd_heel then
    vim.api.nvim_set_current_dir(dir)
  end
end
```
However, I'm not really sure how it may affect other functionality, but seems ok from first look.

**Comment by dzirtusss** [comment]
And some more debugging.

Actually the problem happens only on *newly initialized plugin*. E.g., presuming:
```
/project/README.md
/notebook/index.md
```
and starting in `/project`, no md files loaded yet
 
1. when first opened `README.md`, plugin is initialized, but can't find notebook and NOT change directory because `init.root_dir` returns nil. Later it is possible to open ANY file, and plugin does not change directory.
 1. when first opened `index.md`, initialization happens in a wrong way (w/o honoring `nvim_wd_heel`), and plugin changes directory to `/notebook` because `init.root_dir` returns not nil.
    
so all happens only on first run in initialization.

I've tried to look how to bypass this, but it seems so tied into this logic, so I'm not sure not to brake something @jakewvincent if you might have a time to look would be fabulos.

Atm, I've done a following fix: (leaving for all who will stumble on this thread)
```lua
function MyKeepCd(cmd)
  local original_cwd = vim.fn.getcwd(-1, -1)

  local success, err = pcall(function()
    vim.cmd(cmd)
  end)

  vim.cmd('cd ' .. vim.fn.fnameescape(original_cwd))

  if not success then
    error(err)
  end
end

nmap('<leader>w', '<cmd>lua MyKeepCd("e ~/..../index.md")<CR>')
```
which mitigates the problem, but... surely not solves it.
