### ISSUE TITLE
utf-8 warning with non-utf8-symbols

### ISSUE THREAD

**Issue by jg-schwarz** [jakewvincent/mkdnflow.nvim#58]
Hi and thanks for this wonderful plugin!

Just a small irritation: mkdnflow constantly tells me that one of my "to-do symbols is a utf8 symbol, but the lua-utf8 dependency could not be found". 
I didn't install the dependency, because, actually, I just try to use x and o ...

```
to_do = {
       symbols = {' ', 'o', 'x'},
                   update_parents = true,
                   not_started = ' ',
                   in_progress = 'o',
                   complete = 'x'
               }
```
Is there a way around it or can I at least disable the warning message? 
As of now, I have to confirm this at every startup of nvim(-qt)... 

Thank you very much!

**Comment by jakewvincent** [comment]
Thanks for reporting this! I tried out your above config for to-do symbols and was able to reproduce the error message. Turns out the way I was originally calculating which symbols were utf8 symbols was faulty. I just pushed a fix for this to the main branch. Do you mind pulling the update and letting me know if the issue is resolved?

**Comment by jg-schwarz** [comment]
That fixed it, thanks a lot! 
(BTW: Unfortunately, I ran into #55 ...)

**Comment by jakewvincent** [comment]
Strange--not sure what I did there. Glad the fix for this issue worked :).
