### ISSUE TITLE
Feature: MkdnMoveSource updates link references in other files in the notebook/wiki

### ISSUE THREAD

**Issue by avucic** [jakewvincent/mkdnflow.nvim#93]
When file is renamed I'm expecting all link references to the same file in all related files will be updated with the new filename or not?

**Comment by jakewvincent** [comment]
Hi @avucic, thanks for the issue. The behavior you're experiencing is intentional/normal--only the link immediately under the cursor is renamed.

I do think this would be a nice enhancement to add in the future, although something like this will be more computationally expensive than renaming only the link under the cursor (and the cost will scale with the size of the notebook/wiki). I'll keep this on my to-do list but can't promise anything at the moment.

**Comment by jakewvincent** [comment]
Testing this in the dev branch.

**Comment by helins** [comment]
I have thought a lot about this even before encountering this plugin (which is genuinely awesome BTW, and it comes from somehow who knows zettelkasten well, has used Logseq, Obsedian, etc).

This is probably best left to a standard tool like `fd` to handle the heavy workflow. Using a root perspective, `fd` can update links super fast, way faster than any Lua implementation, without requiring any regex or relative logic.

**Comment by jakewvincent** [comment]
FYI: I've reverted the merge commit that brought this feature into the `dev` branch. It's now in its own branch `feat/update-link-everywhere`. The feature needs additional testing and tweaking to make sure it works with all possible perspective settings.
