### ISSUE TITLE
Bug: Can only jump to the first wiki-style link on a line

### ISSUE THREAD

**Issue by lumpsoid** [jakewvincent/mkdnflow.nvim#99]
In my workflow it often happens that more than one link is on one line.
By the behaviour of `mkdnflow` I found that it cannot currently "see" more than one link on a line.
I then tried to find the reason for this behaviour of `mkdnflow`, and found a function `toNextLink` in `mkdnflow.nvim/lua/mkdnflow/cursor.lua`, which relies on the `go_to` function, which iterates the file line by line, and only looks for a pattern once per line.

I tried to find what algorithm [vimwiki](https://github.com/vimwiki/vimwiki) uses and found that those who write this plugin use the `search()` function for a similar action.
`vimwiki/autoload/vimwiki/base.vim`
```vimscript
891 function! vimwiki#base#search_word(wikiRx, cmd) abort                                              
   1 let match_line = search(a:wikiRx, 's'.a:cmd)
   2 if match_line == 0
   3 echomsg 'Vimwiki: Wiki link not found'.
   4 endif 
   5 endfunction
```

Since you didn't want to use vimscript, so you implemented this function in pure lua?
And if I'm going to try to implement, I need to stay away from vimscript, right?

**Comment by lumpsoid** [comment]
if someone will search something around it →
easy and easy workaround if you use [hop.nvim](https://github.com/phaazon/hop.nvim) you could add this function to your hop setup
```lua
vim.keymap.set(
                'n', 
                '<Tab>', 
                [[:lua require"hop".hint_patterns({ multi_windows = true }, "\\[\\[.*\\]\\]")<CR>]], 
                {desc = 'Pattern in all visible buffers'}
)
```
were hints will be created for the pattern – [[wiki-link]]

**Comment by lumpsoid** [comment]
yes, wiki-style links
something like this → [[20221014073339]]

**Comment by jakewvincent** [comment]
@lumpsoid this should be fixed now. This was a simple oversight on my part due to me not using (or properly testing, apparently) wiki-links in my workflow. In the regex pattern for finding wiki-links, I had a greedy search for material in between the brackets `[[...]]`, so effectively, any material in between the start of the first link on a line and the end of the last link in a line was all recognized as part of the same link. If you run a sync and restart neovim, the cursor should now properly jump to wiki-style links.

**Comment by lumpsoid** [comment]
Thank you for you work!
